# Generated by Django 3.1 on 2020-08-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200820_2348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countryattachfile',
            table='countryattachfile',
        ),
    ]
