# Generated by Django 3.1 on 2020-08-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20200820_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryattachfile',
            old_name='country',
            new_name='post',
        ),
    ]
