# Generated by Django 3.1 on 2020-08-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20200821_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryattachfile',
            old_name='post',
            new_name='country',
        ),
    ]
