# Generated by Django 3.1 on 2020-08-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20200822_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryAttachFile',
        ),
    ]
