# Generated by Django 3.1 on 2020-08-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('country', '0009_auto_20200825_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='CREATE DATE'),
        ),
        migrations.AddField(
            model_name='country',
            name='modify_dt',
            field=models.DateTimeField(null=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AddField(
            model_name='country',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
        migrations.AddField(
            model_name='country',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
