# Generated by Django 3.1 on 2020-08-31 13:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='content',
        ),
        migrations.AddField(
            model_name='city',
            name='card_content',
            field=tinymce.models.HTMLField(null=True, verbose_name='CONTENT'),
        ),
        migrations.AddField(
            model_name='city',
            name='main_content',
            field=tinymce.models.HTMLField(null=True, verbose_name='CONTENT'),
        ),
    ]
