# Generated by Django 3.1 on 2020-08-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_city', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City_detailAttachFile',
            new_name='Detail_cityAttachFile',
        ),
    ]
