# Generated by Django 3.1 on 2020-08-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail_city', '0002_auto_20200826_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_cityattachfile',
            name='detail_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='detail_city.detail_city', verbose_name='Detail_city'),
        ),
    ]
