# Generated by Django 3.1 on 2020-09-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200901_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
